/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_markmjw_ndkdemo_util_StringUtil */

#ifndef _Included_cn_markmjw_ndkdemo_util_StringUtil
#define _Included_cn_markmjw_ndkdemo_util_StringUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_markmjw_ndkdemo_util_StringUtil
 * Method:    setNull
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_markmjw_ndkdemo_util_StringUtil_setNull
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
