/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_markmjw_ndkdemo_util_MathUtil */

#ifndef _Included_cn_markmjw_ndkdemo_util_MathUtil
#define _Included_cn_markmjw_ndkdemo_util_MathUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_markmjw_ndkdemo_util_MathUtil
 * Method:    square
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cn_markmjw_ndkdemo_util_MathUtil_square
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
